/**
 * 🍬 Type Sugar - Clean re-exports of generated API types
 *
 * Instead of: components['schemas']['UserRead']
 * Just use:   User
 *
 * AUTO-GENERATED by scripts/generate-models.js
 * Run: pnpm generate:models
 */

import type { components } from './api-types';
