"""index_sync

Revision ID: 21aca93cf768
Revises: 8814cf036b36
Create Date: 2026-01-15 23:25:40.831986

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21aca93cf768"
down_revision: str | Sequence[str] | None = "8814cf036b36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_patients_last_name_trgm",
        "patients",
        ["last_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"last_name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_patients_last_name_trgm",
        table_name="patients",
        postgresql_using="gin",
        postgresql_ops={"last_name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
