"""create calls and tasks tables

Revision ID: 24437e5500b3
Revises: h2i3j4k5l6m7
Create Date: 2026-01-03 15:35:26.086806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24437e5500b3'
down_revision: Union[str, Sequence[str], None] = 'h2i3j4k5l6m7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_agent_id'), 'calls', ['agent_id'], unique=False)
    op.create_index(op.f('ix_calls_organization_id'), 'calls', ['organization_id'], unique=False)
    op.create_index(op.f('ix_calls_patient_id'), 'calls', ['patient_id'], unique=False)
    op.create_index(op.f('ix_calls_status'), 'calls', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tasks_patient_id'), 'tasks', ['patient_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.drop_index(op.f('ix_care_team_org_patient'), table_name='care_team_assignments')
    op.drop_index(op.f('idx_contact_methods_patient'), table_name='contact_methods')
    op.create_index(op.f('ix_contact_methods_patient_id'), 'contact_methods', ['patient_id'], unique=False)
    op.drop_index(op.f('ix_message_participants_user'), table_name='message_participants')
    op.drop_index(op.f('ix_message_threads_org'), table_name='message_threads')
    op.drop_index(op.f('ix_message_threads_updated'), table_name='message_threads')
    op.drop_index(op.f('ix_messages_thread'), table_name='messages')
    op.drop_index(op.f('ix_messages_thread_created'), table_name='messages')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_read'), table_name='notifications')
    op.add_column('patient_proxy_assignments', sa.Column('can_view_profile', sa.Boolean(), nullable=False))
    op.add_column('patient_proxy_assignments', sa.Column('can_view_appointments', sa.Boolean(), nullable=False))
    op.add_column('patient_proxy_assignments', sa.Column('can_message_providers', sa.Boolean(), nullable=False))
    op.add_column('patient_proxy_assignments', sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('patient_proxy_assignments', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_proxy_assignments_patient', 'patient_proxy_assignments', ['patient_id'], unique=False)
    op.create_index('idx_proxy_assignments_proxy', 'patient_proxy_assignments', ['proxy_id'], unique=False)
    op.drop_column('patient_proxy_assignments', 'access_granted_at')
    op.drop_index(op.f('idx_patients_dob'), table_name='patients')
    op.drop_index(op.f('idx_patients_first_name_trgm'), table_name='patients', postgresql_ops={'first_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_patients_last_name_trgm'), table_name='patients', postgresql_ops={'last_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_patients_mrn'), table_name='patients')
    op.drop_index(op.f('idx_patients_mrn_trgm'), table_name='patients', postgresql_ops={'medical_record_number': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('providers', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('providers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_providers_org_npi'), table_name='providers', postgresql_where='(npi_number IS NOT NULL)')
    op.create_table_comment(
        'providers',
        'Provider profiles with NPI validation',
        existing_comment=None,
        schema=None
    )
    op.alter_column('staff', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('staff', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_user_sessions_active'), table_name='user_sessions')
    op.drop_index(op.f('idx_user_sessions_firebase_uid'), table_name='user_sessions')
    op.drop_index(op.f('idx_user_sessions_user_id'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.create_index(op.f('idx_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_sessions_firebase_uid'), 'user_sessions', ['firebase_uid'], unique=False)
    op.create_index(op.f('idx_user_sessions_active'), 'user_sessions', ['user_id', 'is_revoked'], unique=False)
    op.alter_column('staff', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('staff', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table_comment(
        'providers',
        existing_comment='Provider profiles with NPI validation',
        schema=None
    )
    op.create_index(op.f('ix_providers_org_npi'), 'providers', ['organization_id', 'npi_number'], unique=True, postgresql_where='(npi_number IS NOT NULL)')
    op.alter_column('providers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('providers', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_patients_mrn_trgm'), 'patients', ['medical_record_number'], unique=False, postgresql_ops={'medical_record_number': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_patients_mrn'), 'patients', ['medical_record_number'], unique=False)
    op.create_index(op.f('idx_patients_last_name_trgm'), 'patients', ['last_name'], unique=False, postgresql_ops={'last_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_patients_first_name_trgm'), 'patients', ['first_name'], unique=False, postgresql_ops={'first_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_patients_dob'), 'patients', ['dob'], unique=False)
    op.add_column('patient_proxy_assignments', sa.Column('access_granted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index('idx_proxy_assignments_proxy', table_name='patient_proxy_assignments')
    op.drop_index('idx_proxy_assignments_patient', table_name='patient_proxy_assignments')
    op.drop_column('patient_proxy_assignments', 'revoked_at')
    op.drop_column('patient_proxy_assignments', 'granted_at')
    op.drop_column('patient_proxy_assignments', 'can_message_providers')
    op.drop_column('patient_proxy_assignments', 'can_view_appointments')
    op.drop_column('patient_proxy_assignments', 'can_view_profile')
    op.create_index(op.f('ix_notifications_user_read'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_created'), 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_thread_created'), 'messages', ['thread_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_thread'), 'messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_message_threads_updated'), 'message_threads', ['updated_at'], unique=False)
    op.create_index(op.f('ix_message_threads_org'), 'message_threads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_message_participants_user'), 'message_participants', ['user_id'], unique=False)
    op.drop_index(op.f('ix_contact_methods_patient_id'), table_name='contact_methods')
    op.create_index(op.f('idx_contact_methods_patient'), 'contact_methods', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_team_org_patient'), 'care_team_assignments', ['organization_id', 'patient_id'], unique=False)
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_patient_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_calls_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_patient_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_organization_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_agent_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
