"""add_org_counters

Revision ID: 24dbfc7f6725
Revises: 2dd2736ecb9c
Create Date: 2026-01-15 23:18:41.376174

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24dbfc7f6725"
down_revision: str | Sequence[str] | None = "2dd2736ecb9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("member_count", sa.Integer(), nullable=False)
    )
    op.add_column(
        "organizations", sa.Column("patient_count", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "patient_count")
    op.drop_column("organizations", "member_count")
    # ### end Alembic commands ###
