"""add_patient_billing_manager

Revision ID: 5d19c326cff3
Revises: cdbfddd60ea4
Create Date: 2026-01-15 23:30:43.657326

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d19c326cff3"
down_revision: str | Sequence[str] | None = "cdbfddd60ea4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patients", sa.Column("billing_manager_id", sa.String(length=26), nullable=True)
    )
    op.add_column(
        "patients",
        sa.Column(
            "billing_manager_assigned_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_patients_billing_manager_id"),
        "patients",
        ["billing_manager_id"],
        unique=False,
    )
    op.create_foreign_key(None, "patients", "users", ["billing_manager_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "patients", type_="foreignkey")
    op.drop_index(op.f("ix_patients_billing_manager_id"), table_name="patients")
    op.drop_column("patients", "billing_manager_assigned_at")
    op.drop_column("patients", "billing_manager_id")
    # ### end Alembic commands ###
