"""update_patient_and_add_contacts

Revision ID: 76408be03f50
Revises: 24dbfc7f6725
Create Date: 2026-01-15 23:21:24.214415

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76408be03f50"
down_revision: str | Sequence[str] | None = "24dbfc7f6725"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_methods",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("patient_id", sa.String(length=26), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_safe_for_voicemail", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contact_methods_patient_id"),
        "contact_methods",
        ["patient_id"],
        unique=False,
    )
    op.add_column(
        "patients", sa.Column("first_name", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "patients", sa.Column("last_name", sa.String(length=100), nullable=False)
    )
    op.add_column("patients", sa.Column("gender", sa.String(length=20), nullable=True))
    op.add_column(
        "patients", sa.Column("ssn_last_four", sa.String(length=4), nullable=True)
    )
    op.add_column(
        "patients", sa.Column("preferred_language", sa.String(length=50), nullable=True)
    )
    op.alter_column(
        "patients", "user_id", existing_type=sa.VARCHAR(length=26), nullable=True
    )
    op.create_index(op.f("ix_patients_dob"), "patients", ["dob"], unique=False)
    op.create_index(
        op.f("ix_patients_first_name"), "patients", ["first_name"], unique=False
    )
    op.create_index(
        op.f("ix_patients_last_name"), "patients", ["last_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patients_last_name"), table_name="patients")
    op.drop_index(op.f("ix_patients_first_name"), table_name="patients")
    op.drop_index(op.f("ix_patients_dob"), table_name="patients")
    op.alter_column(
        "patients", "user_id", existing_type=sa.VARCHAR(length=26), nullable=False
    )
    op.drop_column("patients", "preferred_language")
    op.drop_column("patients", "ssn_last_four")
    op.drop_column("patients", "gender")
    op.drop_column("patients", "last_name")
    op.drop_column("patients", "first_name")
    op.drop_index(op.f("ix_contact_methods_patient_id"), table_name="contact_methods")
    op.drop_table("contact_methods")
    # ### end Alembic commands ###
