"""add_mfa_backup_codes

Revision ID: 7d2654ac4899
Revises: 4a597ae96c88
Create Date: 2026-01-15 23:13:54.943228

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d2654ac4899"
down_revision: str | Sequence[str] | None = "4a597ae96c88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("mfa_backup_codes", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "mfa_backup_codes")
    # ### end Alembic commands ###
