"""add_care_teams

Revision ID: 8814cf036b36
Revises: 76408be03f50
Create Date: 2026-01-15 23:24:30.794422

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8814cf036b36"
down_revision: str | Sequence[str] | None = "76408be03f50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "care_team_assignments",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("patient_id", sa.String(length=26), nullable=False),
        sa.Column("provider_id", sa.String(length=26), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"]),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_care_team_assignments_patient_id"),
        "care_team_assignments",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_care_team_assignments_provider_id"),
        "care_team_assignments",
        ["provider_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_patients_last_name_trgm"),
        table_name="patients",
        postgresql_ops={"last_name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_patients_last_name_trgm"),
        "patients",
        ["last_name"],
        unique=False,
        postgresql_ops={"last_name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_care_team_assignments_provider_id"), table_name="care_team_assignments"
    )
    op.drop_index(
        op.f("ix_care_team_assignments_patient_id"), table_name="care_team_assignments"
    )
    op.drop_table("care_team_assignments")
    # ### end Alembic commands ###
