"""add_user_devices

Revision ID: 95576851383f
Revises: 7d2654ac4899
Create Date: 2026-01-15 23:14:50.676009

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95576851383f"
down_revision: str | Sequence[str] | None = "7d2654ac4899"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_devices",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("fcm_token", sa.String(length=255), nullable=False),
        sa.Column("device_name", sa.String(length=100), nullable=True),
        sa.Column("platform", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "fcm_token", name="uix_user_device_token"),
    )
    op.create_index(
        op.f("ix_user_devices_fcm_token"), "user_devices", ["fcm_token"], unique=False
    )
    op.create_index(
        op.f("ix_user_devices_user_id"), "user_devices", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_devices_user_id"), table_name="user_devices")
    op.drop_index(op.f("ix_user_devices_fcm_token"), table_name="user_devices")
    op.drop_table("user_devices")
    # ### end Alembic commands ###
