"""add_timezones

Revision ID: cdbfddd60ea4
Revises: 8e090a79a418
Create Date: 2026-01-15 23:29:47.219543

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdbfddd60ea4"
down_revision: str | Sequence[str] | None = "8e090a79a418"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("timezone", sa.String(length=50), nullable=False)
    )
    op.add_column("users", sa.Column("timezone", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "timezone")
    op.drop_column("organizations", "timezone")
    # ### end Alembic commands ###
