"""add_tasks_and_calls

Revision ID: df0edbedaeab
Revises: c53b4f41d9fa
Create Date: 2026-01-15 23:28:40.614239

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df0edbedaeab"
down_revision: str | Sequence[str] | None = "c53b4f41d9fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call_logs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("agent_user_id", sa.String(length=26), nullable=False),
        sa.Column("patient_id", sa.String(length=26), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("recording_url", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_call_logs_agent_user_id"), "call_logs", ["agent_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_call_logs_organization_id"),
        "call_logs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_call_logs_patient_id"), "call_logs", ["patient_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("assigned_to_user_id", sa.String(length=26), nullable=True),
        sa.Column("patient_id", sa.String(length=26), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_to_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tasks_assigned_to_user_id"),
        "tasks",
        ["assigned_to_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tasks_organization_id"), "tasks", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_patient_id"), "tasks", ["patient_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_patient_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_organization_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_assigned_to_user_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_call_logs_patient_id"), table_name="call_logs")
    op.drop_index(op.f("ix_call_logs_organization_id"), table_name="call_logs")
    op.drop_index(op.f("ix_call_logs_agent_user_id"), table_name="call_logs")
    op.drop_table("call_logs")
    # ### end Alembic commands ###
