/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthNotificationsRouteImport } from './routes/_auth/notifications'
import { Route as AuthMessagesRouteImport } from './routes/_auth/messages'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthTasksIndexRouteImport } from './routes/_auth/tasks/index'
import { Route as AuthSuperAdminIndexRouteImport } from './routes/_auth/super-admin/index'
import { Route as AuthPatientsIndexRouteImport } from './routes/_auth/patients/index'
import { Route as AuthMessagesIndexRouteImport } from './routes/_auth/messages/index'
import { Route as AuthHelpIndexRouteImport } from './routes/_auth/help/index'
import { Route as AuthCallCenterIndexRouteImport } from './routes/_auth/call-center/index'
import { Route as AuthAppointmentsIndexRouteImport } from './routes/_auth/appointments/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthSuperAdminUsersRouteImport } from './routes/_auth/super-admin/users'
import { Route as AuthSuperAdminSystemRouteImport } from './routes/_auth/super-admin/system'
import { Route as AuthSuperAdminOrganizationsRouteImport } from './routes/_auth/super-admin/organizations'
import { Route as AuthProxyPatientsRouteImport } from './routes/_auth/proxy/patients'
import { Route as AuthProxyManagedPatientsBillingRouteImport } from './routes/_auth/proxy/managed-patients-billing'
import { Route as AuthPatientsNewRouteImport } from './routes/_auth/patients/new'
import { Route as AuthPatientsPatientIdRouteImport } from './routes/_auth/patients/$patientId'
import { Route as AuthPatientBillingRouteImport } from './routes/_auth/patient/billing'
import { Route as AuthMessagesThreadIdRouteImport } from './routes/_auth/messages/$threadId'
import { Route as AuthHelpTicketsRouteImport } from './routes/_auth/help/tickets'
import { Route as AuthHelpContactRouteImport } from './routes/_auth/help/contact'
import { Route as AuthAdminStaffRouteImport } from './routes/_auth/admin/staff'
import { Route as AuthAdminProvidersRouteImport } from './routes/_auth/admin/providers'
import { Route as AuthAdminMembersRouteImport } from './routes/_auth/admin/members'
import { Route as AuthAdminBillingRouteImport } from './routes/_auth/admin/billing'
import { Route as AuthAdminAuditLogsRouteImport } from './routes/_auth/admin/audit-logs'
import { Route as AuthProxyManagedPatientsManagedPatientIdBillingRouteImport } from './routes/_auth/proxy/managed-patients/$managedPatientId/billing'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificationsRoute = AuthNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMessagesRoute = AuthMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTasksIndexRoute = AuthTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSuperAdminIndexRoute = AuthSuperAdminIndexRouteImport.update({
  id: '/super-admin/',
  path: '/super-admin/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientsIndexRoute = AuthPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMessagesIndexRoute = AuthMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMessagesRoute,
} as any)
const AuthHelpIndexRoute = AuthHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallCenterIndexRoute = AuthCallCenterIndexRouteImport.update({
  id: '/call-center/',
  path: '/call-center/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppointmentsIndexRoute = AuthAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSuperAdminUsersRoute = AuthSuperAdminUsersRouteImport.update({
  id: '/super-admin/users',
  path: '/super-admin/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSuperAdminSystemRoute = AuthSuperAdminSystemRouteImport.update({
  id: '/super-admin/system',
  path: '/super-admin/system',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSuperAdminOrganizationsRoute =
  AuthSuperAdminOrganizationsRouteImport.update({
    id: '/super-admin/organizations',
    path: '/super-admin/organizations',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProxyPatientsRoute = AuthProxyPatientsRouteImport.update({
  id: '/proxy/patients',
  path: '/proxy/patients',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProxyManagedPatientsBillingRoute =
  AuthProxyManagedPatientsBillingRouteImport.update({
    id: '/proxy/managed-patients-billing',
    path: '/proxy/managed-patients-billing',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthPatientsNewRoute = AuthPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientsPatientIdRoute = AuthPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientBillingRoute = AuthPatientBillingRouteImport.update({
  id: '/patient/billing',
  path: '/patient/billing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMessagesThreadIdRoute = AuthMessagesThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AuthMessagesRoute,
} as any)
const AuthHelpTicketsRoute = AuthHelpTicketsRouteImport.update({
  id: '/help/tickets',
  path: '/help/tickets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHelpContactRoute = AuthHelpContactRouteImport.update({
  id: '/help/contact',
  path: '/help/contact',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminStaffRoute = AuthAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminProvidersRoute = AuthAdminProvidersRouteImport.update({
  id: '/admin/providers',
  path: '/admin/providers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminMembersRoute = AuthAdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminBillingRoute = AuthAdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminAuditLogsRoute = AuthAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProxyManagedPatientsManagedPatientIdBillingRoute =
  AuthProxyManagedPatientsManagedPatientIdBillingRouteImport.update({
    id: '/proxy/managed-patients/$managedPatientId/billing',
    path: '/proxy/managed-patients/$managedPatientId/billing',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/consent': typeof ConsentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthDashboardRoute
  '/messages': typeof AuthMessagesRouteWithChildren
  '/notifications': typeof AuthNotificationsRoute
  '/settings': typeof AuthSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/audit-logs': typeof AuthAdminAuditLogsRoute
  '/admin/billing': typeof AuthAdminBillingRoute
  '/admin/members': typeof AuthAdminMembersRoute
  '/admin/providers': typeof AuthAdminProvidersRoute
  '/admin/staff': typeof AuthAdminStaffRoute
  '/help/contact': typeof AuthHelpContactRoute
  '/help/tickets': typeof AuthHelpTicketsRoute
  '/messages/$threadId': typeof AuthMessagesThreadIdRoute
  '/patient/billing': typeof AuthPatientBillingRoute
  '/patients/$patientId': typeof AuthPatientsPatientIdRoute
  '/patients/new': typeof AuthPatientsNewRoute
  '/proxy/managed-patients-billing': typeof AuthProxyManagedPatientsBillingRoute
  '/proxy/patients': typeof AuthProxyPatientsRoute
  '/super-admin/organizations': typeof AuthSuperAdminOrganizationsRoute
  '/super-admin/system': typeof AuthSuperAdminSystemRoute
  '/super-admin/users': typeof AuthSuperAdminUsersRoute
  '/admin': typeof AuthAdminIndexRoute
  '/appointments': typeof AuthAppointmentsIndexRoute
  '/call-center': typeof AuthCallCenterIndexRoute
  '/help': typeof AuthHelpIndexRoute
  '/messages/': typeof AuthMessagesIndexRoute
  '/patients': typeof AuthPatientsIndexRoute
  '/super-admin': typeof AuthSuperAdminIndexRoute
  '/tasks': typeof AuthTasksIndexRoute
  '/proxy/managed-patients/$managedPatientId/billing': typeof AuthProxyManagedPatientsManagedPatientIdBillingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/consent': typeof ConsentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthDashboardRoute
  '/notifications': typeof AuthNotificationsRoute
  '/settings': typeof AuthSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/audit-logs': typeof AuthAdminAuditLogsRoute
  '/admin/billing': typeof AuthAdminBillingRoute
  '/admin/members': typeof AuthAdminMembersRoute
  '/admin/providers': typeof AuthAdminProvidersRoute
  '/admin/staff': typeof AuthAdminStaffRoute
  '/help/contact': typeof AuthHelpContactRoute
  '/help/tickets': typeof AuthHelpTicketsRoute
  '/messages/$threadId': typeof AuthMessagesThreadIdRoute
  '/patient/billing': typeof AuthPatientBillingRoute
  '/patients/$patientId': typeof AuthPatientsPatientIdRoute
  '/patients/new': typeof AuthPatientsNewRoute
  '/proxy/managed-patients-billing': typeof AuthProxyManagedPatientsBillingRoute
  '/proxy/patients': typeof AuthProxyPatientsRoute
  '/super-admin/organizations': typeof AuthSuperAdminOrganizationsRoute
  '/super-admin/system': typeof AuthSuperAdminSystemRoute
  '/super-admin/users': typeof AuthSuperAdminUsersRoute
  '/admin': typeof AuthAdminIndexRoute
  '/appointments': typeof AuthAppointmentsIndexRoute
  '/call-center': typeof AuthCallCenterIndexRoute
  '/help': typeof AuthHelpIndexRoute
  '/messages': typeof AuthMessagesIndexRoute
  '/patients': typeof AuthPatientsIndexRoute
  '/super-admin': typeof AuthSuperAdminIndexRoute
  '/tasks': typeof AuthTasksIndexRoute
  '/proxy/managed-patients/$managedPatientId/billing': typeof AuthProxyManagedPatientsManagedPatientIdBillingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/_auth': typeof AuthRouteWithChildren
  '/consent': typeof ConsentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/messages': typeof AuthMessagesRouteWithChildren
  '/_auth/notifications': typeof AuthNotificationsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/_auth/admin/audit-logs': typeof AuthAdminAuditLogsRoute
  '/_auth/admin/billing': typeof AuthAdminBillingRoute
  '/_auth/admin/members': typeof AuthAdminMembersRoute
  '/_auth/admin/providers': typeof AuthAdminProvidersRoute
  '/_auth/admin/staff': typeof AuthAdminStaffRoute
  '/_auth/help/contact': typeof AuthHelpContactRoute
  '/_auth/help/tickets': typeof AuthHelpTicketsRoute
  '/_auth/messages/$threadId': typeof AuthMessagesThreadIdRoute
  '/_auth/patient/billing': typeof AuthPatientBillingRoute
  '/_auth/patients/$patientId': typeof AuthPatientsPatientIdRoute
  '/_auth/patients/new': typeof AuthPatientsNewRoute
  '/_auth/proxy/managed-patients-billing': typeof AuthProxyManagedPatientsBillingRoute
  '/_auth/proxy/patients': typeof AuthProxyPatientsRoute
  '/_auth/super-admin/organizations': typeof AuthSuperAdminOrganizationsRoute
  '/_auth/super-admin/system': typeof AuthSuperAdminSystemRoute
  '/_auth/super-admin/users': typeof AuthSuperAdminUsersRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/appointments/': typeof AuthAppointmentsIndexRoute
  '/_auth/call-center/': typeof AuthCallCenterIndexRoute
  '/_auth/help/': typeof AuthHelpIndexRoute
  '/_auth/messages/': typeof AuthMessagesIndexRoute
  '/_auth/patients/': typeof AuthPatientsIndexRoute
  '/_auth/super-admin/': typeof AuthSuperAdminIndexRoute
  '/_auth/tasks/': typeof AuthTasksIndexRoute
  '/_auth/proxy/managed-patients/$managedPatientId/billing': typeof AuthProxyManagedPatientsManagedPatientIdBillingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/consent'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/settings'
    | '/invite/$token'
    | '/legal/privacy'
    | '/legal/terms'
    | '/admin/audit-logs'
    | '/admin/billing'
    | '/admin/members'
    | '/admin/providers'
    | '/admin/staff'
    | '/help/contact'
    | '/help/tickets'
    | '/messages/$threadId'
    | '/patient/billing'
    | '/patients/$patientId'
    | '/patients/new'
    | '/proxy/managed-patients-billing'
    | '/proxy/patients'
    | '/super-admin/organizations'
    | '/super-admin/system'
    | '/super-admin/users'
    | '/admin'
    | '/appointments'
    | '/call-center'
    | '/help'
    | '/messages/'
    | '/patients'
    | '/super-admin'
    | '/tasks'
    | '/proxy/managed-patients/$managedPatientId/billing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/consent'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/invite/$token'
    | '/legal/privacy'
    | '/legal/terms'
    | '/admin/audit-logs'
    | '/admin/billing'
    | '/admin/members'
    | '/admin/providers'
    | '/admin/staff'
    | '/help/contact'
    | '/help/tickets'
    | '/messages/$threadId'
    | '/patient/billing'
    | '/patients/$patientId'
    | '/patients/new'
    | '/proxy/managed-patients-billing'
    | '/proxy/patients'
    | '/super-admin/organizations'
    | '/super-admin/system'
    | '/super-admin/users'
    | '/admin'
    | '/appointments'
    | '/call-center'
    | '/help'
    | '/messages'
    | '/patients'
    | '/super-admin'
    | '/tasks'
    | '/proxy/managed-patients/$managedPatientId/billing'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_auth'
    | '/consent'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_auth/dashboard'
    | '/_auth/messages'
    | '/_auth/notifications'
    | '/_auth/settings'
    | '/invite/$token'
    | '/legal/privacy'
    | '/legal/terms'
    | '/_auth/admin/audit-logs'
    | '/_auth/admin/billing'
    | '/_auth/admin/members'
    | '/_auth/admin/providers'
    | '/_auth/admin/staff'
    | '/_auth/help/contact'
    | '/_auth/help/tickets'
    | '/_auth/messages/$threadId'
    | '/_auth/patient/billing'
    | '/_auth/patients/$patientId'
    | '/_auth/patients/new'
    | '/_auth/proxy/managed-patients-billing'
    | '/_auth/proxy/patients'
    | '/_auth/super-admin/organizations'
    | '/_auth/super-admin/system'
    | '/_auth/super-admin/users'
    | '/_auth/admin/'
    | '/_auth/appointments/'
    | '/_auth/call-center/'
    | '/_auth/help/'
    | '/_auth/messages/'
    | '/_auth/patients/'
    | '/_auth/super-admin/'
    | '/_auth/tasks/'
    | '/_auth/proxy/managed-patients/$managedPatientId/billing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AuthRoute: typeof AuthRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notifications': {
      id: '/_auth/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthNotificationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/messages': {
      id: '/_auth/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthMessagesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tasks/': {
      id: '/_auth/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthTasksIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/super-admin/': {
      id: '/_auth/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthSuperAdminIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patients/': {
      id: '/_auth/patients/'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthPatientsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/messages/': {
      id: '/_auth/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthMessagesIndexRouteImport
      parentRoute: typeof AuthMessagesRoute
    }
    '/_auth/help/': {
      id: '/_auth/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthHelpIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/call-center/': {
      id: '/_auth/call-center/'
      path: '/call-center'
      fullPath: '/call-center'
      preLoaderRoute: typeof AuthCallCenterIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/appointments/': {
      id: '/_auth/appointments/'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthAppointmentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/super-admin/users': {
      id: '/_auth/super-admin/users'
      path: '/super-admin/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AuthSuperAdminUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/super-admin/system': {
      id: '/_auth/super-admin/system'
      path: '/super-admin/system'
      fullPath: '/super-admin/system'
      preLoaderRoute: typeof AuthSuperAdminSystemRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/super-admin/organizations': {
      id: '/_auth/super-admin/organizations'
      path: '/super-admin/organizations'
      fullPath: '/super-admin/organizations'
      preLoaderRoute: typeof AuthSuperAdminOrganizationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/proxy/patients': {
      id: '/_auth/proxy/patients'
      path: '/proxy/patients'
      fullPath: '/proxy/patients'
      preLoaderRoute: typeof AuthProxyPatientsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/proxy/managed-patients-billing': {
      id: '/_auth/proxy/managed-patients-billing'
      path: '/proxy/managed-patients-billing'
      fullPath: '/proxy/managed-patients-billing'
      preLoaderRoute: typeof AuthProxyManagedPatientsBillingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patients/new': {
      id: '/_auth/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthPatientsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patients/$patientId': {
      id: '/_auth/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthPatientsPatientIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patient/billing': {
      id: '/_auth/patient/billing'
      path: '/patient/billing'
      fullPath: '/patient/billing'
      preLoaderRoute: typeof AuthPatientBillingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/messages/$threadId': {
      id: '/_auth/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof AuthMessagesThreadIdRouteImport
      parentRoute: typeof AuthMessagesRoute
    }
    '/_auth/help/tickets': {
      id: '/_auth/help/tickets'
      path: '/help/tickets'
      fullPath: '/help/tickets'
      preLoaderRoute: typeof AuthHelpTicketsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/help/contact': {
      id: '/_auth/help/contact'
      path: '/help/contact'
      fullPath: '/help/contact'
      preLoaderRoute: typeof AuthHelpContactRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/staff': {
      id: '/_auth/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthAdminStaffRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/providers': {
      id: '/_auth/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthAdminProvidersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/members': {
      id: '/_auth/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthAdminMembersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/billing': {
      id: '/_auth/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthAdminBillingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/audit-logs': {
      id: '/_auth/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthAdminAuditLogsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/proxy/managed-patients/$managedPatientId/billing': {
      id: '/_auth/proxy/managed-patients/$managedPatientId/billing'
      path: '/proxy/managed-patients/$managedPatientId/billing'
      fullPath: '/proxy/managed-patients/$managedPatientId/billing'
      preLoaderRoute: typeof AuthProxyManagedPatientsManagedPatientIdBillingRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthMessagesRouteChildren {
  AuthMessagesThreadIdRoute: typeof AuthMessagesThreadIdRoute
  AuthMessagesIndexRoute: typeof AuthMessagesIndexRoute
}

const AuthMessagesRouteChildren: AuthMessagesRouteChildren = {
  AuthMessagesThreadIdRoute: AuthMessagesThreadIdRoute,
  AuthMessagesIndexRoute: AuthMessagesIndexRoute,
}

const AuthMessagesRouteWithChildren = AuthMessagesRoute._addFileChildren(
  AuthMessagesRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthMessagesRoute: typeof AuthMessagesRouteWithChildren
  AuthNotificationsRoute: typeof AuthNotificationsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthAdminAuditLogsRoute: typeof AuthAdminAuditLogsRoute
  AuthAdminBillingRoute: typeof AuthAdminBillingRoute
  AuthAdminMembersRoute: typeof AuthAdminMembersRoute
  AuthAdminProvidersRoute: typeof AuthAdminProvidersRoute
  AuthAdminStaffRoute: typeof AuthAdminStaffRoute
  AuthHelpContactRoute: typeof AuthHelpContactRoute
  AuthHelpTicketsRoute: typeof AuthHelpTicketsRoute
  AuthPatientBillingRoute: typeof AuthPatientBillingRoute
  AuthPatientsPatientIdRoute: typeof AuthPatientsPatientIdRoute
  AuthPatientsNewRoute: typeof AuthPatientsNewRoute
  AuthProxyManagedPatientsBillingRoute: typeof AuthProxyManagedPatientsBillingRoute
  AuthProxyPatientsRoute: typeof AuthProxyPatientsRoute
  AuthSuperAdminOrganizationsRoute: typeof AuthSuperAdminOrganizationsRoute
  AuthSuperAdminSystemRoute: typeof AuthSuperAdminSystemRoute
  AuthSuperAdminUsersRoute: typeof AuthSuperAdminUsersRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthAppointmentsIndexRoute: typeof AuthAppointmentsIndexRoute
  AuthCallCenterIndexRoute: typeof AuthCallCenterIndexRoute
  AuthHelpIndexRoute: typeof AuthHelpIndexRoute
  AuthPatientsIndexRoute: typeof AuthPatientsIndexRoute
  AuthSuperAdminIndexRoute: typeof AuthSuperAdminIndexRoute
  AuthTasksIndexRoute: typeof AuthTasksIndexRoute
  AuthProxyManagedPatientsManagedPatientIdBillingRoute: typeof AuthProxyManagedPatientsManagedPatientIdBillingRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthMessagesRoute: AuthMessagesRouteWithChildren,
  AuthNotificationsRoute: AuthNotificationsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthAdminAuditLogsRoute: AuthAdminAuditLogsRoute,
  AuthAdminBillingRoute: AuthAdminBillingRoute,
  AuthAdminMembersRoute: AuthAdminMembersRoute,
  AuthAdminProvidersRoute: AuthAdminProvidersRoute,
  AuthAdminStaffRoute: AuthAdminStaffRoute,
  AuthHelpContactRoute: AuthHelpContactRoute,
  AuthHelpTicketsRoute: AuthHelpTicketsRoute,
  AuthPatientBillingRoute: AuthPatientBillingRoute,
  AuthPatientsPatientIdRoute: AuthPatientsPatientIdRoute,
  AuthPatientsNewRoute: AuthPatientsNewRoute,
  AuthProxyManagedPatientsBillingRoute: AuthProxyManagedPatientsBillingRoute,
  AuthProxyPatientsRoute: AuthProxyPatientsRoute,
  AuthSuperAdminOrganizationsRoute: AuthSuperAdminOrganizationsRoute,
  AuthSuperAdminSystemRoute: AuthSuperAdminSystemRoute,
  AuthSuperAdminUsersRoute: AuthSuperAdminUsersRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthAppointmentsIndexRoute: AuthAppointmentsIndexRoute,
  AuthCallCenterIndexRoute: AuthCallCenterIndexRoute,
  AuthHelpIndexRoute: AuthHelpIndexRoute,
  AuthPatientsIndexRoute: AuthPatientsIndexRoute,
  AuthSuperAdminIndexRoute: AuthSuperAdminIndexRoute,
  AuthTasksIndexRoute: AuthTasksIndexRoute,
  AuthProxyManagedPatientsManagedPatientIdBillingRoute:
    AuthProxyManagedPatientsManagedPatientIdBillingRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AuthRoute: AuthRouteWithChildren,
  ConsentRoute: ConsentRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
